### ISSUE TITLE
Click function won't work if browser or page is not focused in Chrome

### ISSUE THREAD

**Issue by berkaey** [alexgibson/notify.js#31] opened 2014-12-17 08:24 UTC
yeah basically "Click function won't work if browser or page is not focused"
the notification is just close.
Is this function needs to be simple like window.open or something ?

**Comment by alexgibson** [comment] 2015-01-10 13:26
I've done some testing in Chrome and `click` events do fire as expected if: 

* the browser page is not focused
* the browser page is not the active tab
* the browser is not the focuses application
* the browser is minimized

As far as this library goes, it functions as expected. If things aren't happening as you intend in your application if the tab is not active, then this must be due to some logic in your application, not this library.

I could add a `window.focus()` in the callback, but then this adds unexpected behavior for other users who might not either need or expect this behavior.

Closing, but thanks anyway for the suggestion.

**Closed by alexgibson** 2015-01-10 13:26 UTC
