### ISSUE TITLE
Notify is not defined

### ISSUE THREAD

**Issue by Aksh0377** [alexgibson/notify.js#80] opened 2017-10-04 05:54 UTC
it occures when write

var myNotification = new Notify('Yo dawg!', {
    body: 'This is an awesome notification',
    notifyShow: onNotifyShow
});
 
function onNotifyShow() {
    console.log('notification was shown!');
}.
it will give notify not define error ("i am not using require here").

and if i use require like:

var Notify = require('notifyjs')
var myNotification = new Notify('Yo dawg!', {
    body: 'This is an awesome notification',
    notifyShow: onNotifyShow
});
 
function onNotifyShow() {
    console.log('notification was shown!');
}.

then it shows 
/Volumes/Project data/node/demo/node_modules/notifyjs/dist/notify.js:63
var N = window.Notification;
              ^
window is not defined.
please help

**Comment by alexgibson** [comment] 2017-10-04 10:16
This works OK for me when using Browserify. You are running CommonJS in the browser, right? (`window` is not defined in Node).

**Comment by Aksh0377** [comment] 2017-10-06 08:07
i am also using browsify but still the same problem, actually i am new in nodeJS can you guide me how can i solve this problem and show notification in browser, what should i do?

**Comment by alexgibson** [comment] 2017-10-06 08:19
There’s an example demo in the repo for how to use the Library. Sorry but I can’t help you based just on the information you have provided alone. I donut think the problem is with this library though.

**Comment by alexgibson** [comment] 2017-10-06 08:26
If you can provide a reduced test case on how to reproduce this issue I can try and help (please don't link me the entire contents of your repo). The title of this issue is also a bit confusing since it's titled "`Notify` of not defined", yet in the description you reference "`window` is not defined" instead.

**Comment by Aksh0377** [comment] 2017-10-06 08:40
Thanks for quick response , and  i have specified both scenarios where "Notify not defined " & "window is not defined" error, i am getting different errors while using NotifyJs

**Comment by alexgibson** [comment] 2017-10-06 09:56
Like I already said, I can't help you much from a single error messag alone with no context or example for how you're loading the library.

There's already an example in this repo that shows you what you need to do to load the library using a regular browser global. For CommonJS, following the basic "Hello World" example on the Browserify home page with this library works for me: http://browserify.org/

**Comment by alexgibson** [comment] 2017-10-10 06:52
Closing this as “works for me” and due to lack of information. If you want to reopen this, please feel free to and provide a test case. Thanks

**Closed by alexgibson** 2017-10-10 06:52 UTC
Labels: awaiting feedback
